### ISSUE TITLE
Define schema for Questions

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmsp_backend_prototype#64]
Review Template Builder wireframes
Decide what fields needs to be stored in a table
What queries and mutations the front end needs

![Image](https://github.com/user-attachments/assets/6f6c318e-d090-4eaf-a348-6b7bf4bfb4be)

Options tab
<img width="698" alt="Screenshot 2024-08-29 at 4 13 11 PM" src="https://github.com/user-attachments/assets/e36e7950-f68f-48df-80cd-9b6f8ec520fe">

Logic tab
<img width="643" alt="Screenshot 2024-08-29 at 4 13 17 PM" src="https://github.com/user-attachments/assets/8777568a-0572-4d4f-b542-0060f63c4530">

**Comment by briri** [comment]
### Queries
- questionTypes(): QuestionType[]
- questions(sectionId: Int!): Question[]
- question(questionId: Int!): Question
- publishedQuestions(sectionId: Int!): VersionedQuestion[]
- questionConditions(questionId: Int!): QuestionCondition[]

### Mutations
- addQuestion(sectionId: Int!, questionTypeId Int!): Question
- changeQuestionType(questionId: Int!, questionTypeId Int!): Question
- updateQuestion(questionId: Int!, displayOrder: Int, questionText: String, requirementText: String, guidanceText: String, sampleText: String, required: Boolean): Question
- removeQuestion(questionId: Int!): Boolean
- addQuestionCondition(questionId: Int!, action: String!, condition: String!, conditionMatch: String, target: String!): QuestionCondition
- updateQuestionCondition(questionConditionId: Int!, action: String!, condition: String!, conditionMatch: String, target: String!): QuestionCondition
- removeQuestionCondition(questionConditionId: Int!): Boolean

### Question
- **id** Int! 
- **createdById** Int! (FK to User)
- **created** DateTime! (default current timestamp)
- **modifiedById** Int! (FK to User)
- **modified** DateTime! (default current timestamp)
- **templateId** Int! (FK to Template)
- **sectionId** Int! (FK to Section)
- **displayOrder** Int! (default: whatever the next position number is for the section)
- **isDirty** Boolean! (default: false) (indicates whether or not the question has changed since the template was last published)
- **questionTypeId** Int! (FK to QuestionType)
- **questionText** String
- **requirementText** String
- **guidanceText** String
- **sampleText** String
- **required** Boolean (default: false)

### QuestionType
- **id** Int! 
- **createdById** Int! (FK to User)
- **created** DateTime! (default current timestamp)
- **modifiedById** Int! (FK to User)
- **modified** DateTime! (default current timestamp)
- **name** String!
- **usageDescription** Text!

### VersionedQuestion
- **id** Int! 
- **createdById** Int! (FK to User)
- **created** DateTime! (default current timestamp)
- **modifiedById** Int! (FK to User)
- **modified** DateTime! (default current timestamp)
- **versionedTemplateId** Int! (FK to Template)
- **versionedSectionId** Int! (FK to Section)
- **displayOrder** Int! (default: whatever the next position number is for the section)
- **questionTypeId** Int! (FK to QuestionType)
- **questionText** String
- **requirementText** String
- **guidanceText** String
- **sampleText** String
- **required** Boolean (default: false)

### QuestionCondition
- **id** Int! 
- **createdById** Int! (FK to User)
- **created** DateTime! (default current timestamp)
- **modifiedById** Int! (FK to User)
- **modified** DateTime! (default current timestamp)
- **questionId** Int! (FK to Question)
- **action** String! (default: SHOW_QUESTION) (enum options: SHOW_QUESTION, HIDE_QUESTION, SEND_EMAIL)
- **condition** String! (default: HAS_ANSWER) (enum options: HAS_ANSWER, EQUAL, DOES_NOT_EQUAL, INCLUDES)
- **conditionMatch** String (default: null) (relative to the condition type, HAS_ANSWER should be null, others should have a value. for example a condition of `DOES_NOT_EQUAL` could have `Yes` as its `conditionMatch`)
- **target** String! (the target of the action. An email address for SEND_EMAIL and a Question Id otherwise)

### Other Logic
- I think the filter/search on the select a Question Type page could just be handled on the client side. I can't envision more than a few dozen or so types
- We may need to blank out or remove certain data if the user switches the type of a question. For example if it was a select box and they switch to a text field, we should remove the selection options.
- isDirty flags cascade up. Meaning that if a question is edited/added/removed the related Section and Template's isDirty flag should be set to true (this logic should be added to the TemplateService)
- if a QuestionCondition is added/edited/deleted then the related Question's isDirty flag should be set to true
- QuestionConditions consist of several fields that we will use to store the boolean logic which can be stored/retrieved as `if [Question content] [condition] [conditionMatch] then [action] on [target]` so for example `if 'Yes' EQUAL 'Yes' then 'SHOW_Question' 123`

**Comment by briri** [comment]
@andrewebdev @fraserclark @jupiter007 I took a first pass at defining an initial schema for the Question pages. Let me know what you think.

**Comment by andrewebdev** [comment]
I'll get to this at some point this evening or tomorrow morning ;)

**Comment by jupiter007** [comment]
@briri could you copy a screenshot of the Questions page to this ticket?

**Comment by briri** [comment]
thanks for adding the main screenshot @jupiter007 I added the 2 additional tabs underneath

**Comment by jupiter007** [comment]
@briri 

1) Do the `questionTypes` refer to a question from our library? If a user adds their own question that doesn't have a questionType, then the "questionType" variable should not be required on "addQuestion()

Also, when would the mutation be made to add a question? I would think we would want to call that mutation only after the user clicks `Save` on the Question page. If so, we would want to pass all the other field values in as variables to "addQuestion()" mutation.

2) Do we need to add a mutation to set the "Options" info, like "is this field required?".

Some unrelated notes on page functionality:
1) Should the option to change Question Type be at the top of the form, since it could change the fields below it?

2) In regards to `removeQuestionCondition` mutation, do we currently have a way in the wireframe to remove a condition?

**Comment by briri** [comment]
The question types refer to whether or not it's a text field, select box, radio buttons, etc. I'm fine if we just use an enum for this. The UI is going to need it though to determine how to display they element when the user is answering the question.

We can adjust the `addQuestion` mutation to pass in whatever fields are needed/available in the UI.

You figured you could just call `updateQuestion` on the Options tab like in the Text tab. We can add individual mutations though if it's easier on the frontend.

Yeah, there isn't a way in the wireframe to remove a condition or add additional ones. It is required. I assumed it was just an oversight

**Comment by jupiter007** [comment]
Having a separate mutation for `updateOptions` might be easier, since it has it's own "Save" button.

**Comment by briri** [comment]
👍🏻 I added it above

**Comment by andrewebdev** [comment]
Just a nitpick about `updateOptions`, it should probably be `updateQuestionOptions` for consistency?
Other than that everything else looks okay for a start.

**Comment by briri** [comment]
yes, good catch. I updated it to `updateQuestionOptions`
